spring.application.name=oficina-ddd
# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/oficina_db
spring.datasource.username=oficina_user
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate para criar/atualizar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostra as queries SQL no console (útil para desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
