spring.application.name=oficina-ddd

#usuário e senha admin da aplicação
app.admin.default-user=${ADMIN_USER:admin}
app.admin.default-password=${ADMIN_PASSWORD:admin123}

server.port=8080

api.security.token.secret=o0RCmGOXvcpRakIn4pobXEI3Xx59r5BDleP7

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/oficina_db
spring.datasource.username=oficina_user
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate para criar/atualizar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra as queries SQL no console (útil para desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Springdoc / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.paths-to-scan=/api/v1
springdoc.show-actuator=false

logging.level.root=INFO